pipeline {
    
    agent any
    
    options {
        disableConcurrentBuilds()
    }
    
    stages {
        
        stage('Build') {
        	steps {
	            sh 'mvn -f spring-boot-demo/pom.xml clean install -DskipTests'
	        }   
        }
        
        stage('Unin Tests') {
        	steps {
	            sh 'mvn -f spring-boot-demo/pom.xml clean install'
	        }   
        }
        
        stage('Sonar Scan') {
        	// def scannerHome = tool 'sonar-scanner'
        	//steps{
            	//def scannerHome = tool name: 'sonar-scanner'
            	
            	// , type: 'hudson.plugins.sonar.SonarRunnerInstallation'
    		//	withSonarQubeEnv('sonar-server') {
      			//		sh "${scannerHome}/bin/sonar-scanner"    
        	//	}
        			
        	//	timeout(time: 5, unit: 'MINUTES') { 
    			//	waitForQualityGate abortPipeline: true
  			//	}
            
        	//}
        	
	        	 environment {
				    SCANNER_HOME = tool 'sonar-scanner'
  				 }
			      steps {
			        withSonarQubeEnv('sonar-server') {
			          sh "${SCANNER_HOME}/bin/sonar-scanner -Dproject.settings=spring-boot-demo/sonar-project.properties"
			        }
			      }
    	}
    	
    	stage('Build Docker Image') {
    		steps{
				println "Building image"
			}
    	
    	}
    	
    	stage('Publish to DockerHub') {
			steps{	
				println "Pushing Image to Docker Hub"
			}
    	
    	}
    	
    	stage('Deploy') {
    		steps{
    	    	println "Deploying.."
    		}
    	
    	}
    	
    	
    }
}